import { Check, ChevronDown, ChevronRight, CircleAlert, CircleCheck, Clock3, Download, Folder, FolderPlus, Github, LoaderCircle, Moon, Plus, RefreshCw, Settings2, Sun, Trash2, Upload, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { flushSync } from "react-dom";
import { api } from "./api";
import type { AppConfig, FolderGroup, RootDirectory, SyncItem, SyncPreview } from "./domain";

const EMPTY_CONFIG: AppConfig = { schemaVersion: 3, rootDirectories: [], folderGroups: [], items: [] };
const NOTIFICATION_TIMEOUT_MS = 5_000;
type Dialog = "group" | "sources" | "settings" | "sync-scope" | "preview" | "delete" | "delete-item" | "move" | "import" | null;
type Operation = { kind: "preview" | "sync"; current: number; total: number; itemName?: string };
type Node = { path: string; label: string; children: Node[] };
const id = () => crypto.randomUUID();
const errorMessage = (cause: unknown, fallback: string) => {
  if (cause instanceof Error && cause.message) return cause.message;
  if (typeof cause === "string" && cause) return cause;
  if (cause && typeof cause === "object" && "message" in cause && typeof cause.message === "string") return cause.message;
  return fallback;
};
const normalize = (value: string) => { const path = value.trim().replaceAll("\\", "/").replace(/^\/+|\/+$/g, ""); if (!path || path.split("/").some((part) => !part || part === "." || part === "..")) throw new Error("请输入普通的、相对当前根目录的文件夹路径。"); return path; };
const itemPath = (item: SyncItem) => [item.folderGroup, item.destinationName].filter(Boolean).join("/");
const localPath = (root: RootDirectory | undefined, item: SyncItem) => root ? `${root.path}/${itemPath(item)}` : itemPath(item);
const contains = (base: string, value: string) => !base || value === base || value.startsWith(`${base}/`);
function tree(paths: string[]) { const roots: Node[] = []; const map = new Map<string, Node>(); for (const path of [...new Set(paths)].filter(Boolean).sort()) { let parent = roots; for (const [index, label] of path.split("/").entries()) { const current = path.split("/").slice(0, index + 1).join("/"); let node = map.get(current); if (!node) { node = { path: current, label, children: [] }; map.set(current, node); parent.push(node); } parent = node.children; } } return roots; }
function parseSource(url: string, rootId: string, folderGroup: string, destinationName?: string): SyncItem { const parsed = new URL(url.trim()); const parts = parsed.pathname.split("/").filter(Boolean); if (parsed.hostname !== "github.com" || parts.length < 2) throw new Error("请使用 GitHub 仓库或目录链接。"); const [owner, repo, marker, branch, ...sourceParts] = parts; if (marker && marker !== "tree") throw new Error("请使用仓库链接或 GitHub 的 tree 目录链接。"); if (marker === "tree" && (!branch || !sourceParts.length)) throw new Error("目录链接必须包含分支与目录。"); const sourcePath = marker === "tree" ? sourceParts.join("/") : undefined; return { id: id(), sourceUrl: url.trim(), repoUrl: `https://github.com/${owner}/${repo}.git`, branch: marker === "tree" ? branch : undefined, sourcePath, rootId, folderGroup, destinationName: destinationName?.trim() || sourcePath?.split("/").at(-1) || repo, mirror: true, lastStatus: "not_synced" }; }
function Status({ item }: { item: SyncItem }) { const Icon = item.lastStatus === "failed" ? CircleAlert : item.lastStatus === "synced" ? CircleCheck : Clock3; return <span className={`status status-${item.lastStatus}`}><Icon size={14} />{{ not_synced: "未同步", synced: "已同步", failed: "失败" }[item.lastStatus]}</span>; }

export default function App() {
  const [config, setConfig] = useState<AppConfig>(EMPTY_CONFIG); const [loaded, setLoaded] = useState(false); const [rootId, setRootId] = useState<string>(); const [group, setGroup] = useState(""); const [dialog, setDialog] = useState<Dialog>(null); const [selectedId, setSelectedId] = useState<string>(); const [operation, setOperation] = useState<Operation>(); const [previews, setPreviews] = useState<Array<{ item: SyncItem; preview: SyncPreview }>>([]); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [groupPath, setGroupPath] = useState(""); const [urls, setUrls] = useState(""); const [customName, setCustomName] = useState(""); const [recursive, setRecursive] = useState(true); const [deleteFiles, setDeleteFiles] = useState(false); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [dropTarget, setDropTarget] = useState<string>(); const draggedId = useRef<string>(); const sidebarRef = useRef<HTMLElement>(null); const [pendingMove, setPendingMove] = useState<{ item: SyncItem; rootId: string; group: string }>(); const [moveFiles, setMoveFiles] = useState(false); const [pendingImport, setPendingImport] = useState<AppConfig>(); const [pendingDelete, setPendingDelete] = useState<SyncItem>();
  useEffect(() => { api.loadConfig().then((next) => { setConfig(next); setRootId(next.rootDirectories[0]?.id); }).catch(() => setConfig(EMPTY_CONFIG)).finally(() => setLoaded(true)); }, []);
  useEffect(() => { if (!error) return; const timeout = window.setTimeout(() => setError(undefined), NOTIFICATION_TIMEOUT_MS); return () => window.clearTimeout(timeout); }, [error]);
  useEffect(() => { if (!notice) return; const timeout = window.setTimeout(() => setNotice(undefined), NOTIFICATION_TIMEOUT_MS); return () => window.clearTimeout(timeout); }, [notice]);
  const persist = async (next: AppConfig) => { setConfig(next); try { await api.saveConfig(next); } catch (cause) { setError(errorMessage(cause, "配置无法保存。")); } };
  const root = config.rootDirectories.find((candidate) => candidate.id === rootId); const currentGroups = config.folderGroups.filter((candidate) => candidate.rootId === rootId); const nodes = useMemo(() => tree(currentGroups.map((candidate) => candidate.path)), [currentGroups]); const currentItems = config.items.filter((item) => item.rootId === rootId && (recursive ? contains(group, item.folderGroup) : item.folderGroup === group)); const directItems = config.items.filter((item) => item.rootId === rootId && item.folderGroup === group); const selected = config.items.find((item) => item.id === selectedId); const theme = config.theme ?? "light";
  const setLocation = (nextRootId: string, nextGroup = "") => { setRootId(nextRootId); setGroup(nextGroup); setSelectedId(undefined); };
  const addRoot = async () => { const path = await api.selectRoot().catch(() => null); if (!path) return; if (config.rootDirectories.some((candidate) => candidate.path === path)) return setError("该根目录已存在。"); const next = { ...config, rootDirectories: [...config.rootDirectories, { id: id(), path }] }; await persist(next); setLocation(next.rootDirectories.at(-1)!.id); };
  const addGroup = async () => { try { if (!rootId) throw new Error("请先添加并选择一个根目录。"); const path = normalize(groupPath); if (currentGroups.some((candidate) => candidate.path === path)) throw new Error("该文件夹组已存在。"); if (config.items.some((item) => item.rootId === rootId && (path === itemPath(item) || path.startsWith(`${itemPath(item)}/`)))) throw new Error("文件夹组不能位于同步项目标目录内。"); await persist({ ...config, folderGroups: [...config.folderGroups, { rootId, path }] }); setGroup(path); setGroupPath(""); setDialog(null); } catch (cause) { setError(errorMessage(cause, "无法创建文件夹组。")); } };
  const addSources = async () => { try { if (!rootId) throw new Error("请先选择根目录。"); const links = urls.split("\n").map((line) => line.trim()).filter(Boolean); if (!links.length) throw new Error("请至少粘贴一个 GitHub 链接。"); if (customName.trim() && links.length !== 1) throw new Error("批量添加时请保留自动名称。"); const additions = links.map((url) => parseSource(url, rootId, group, customName)); const paths = new Set(config.items.filter((item) => item.rootId === rootId).map(itemPath)); for (const item of additions) { if (paths.has(itemPath(item))) throw new Error(`目标路径已存在：${itemPath(item)}`); paths.add(itemPath(item)); } await persist({ ...config, items: [...config.items, ...additions] }); setSelectedId(additions[0].id); setUrls(""); setCustomName(""); setDialog(null); } catch (cause) { setError(errorMessage(cause, "链接无法解析。")); } };
  const preview = async (items: SyncItem[]) => { if (!items.length || !root) return; flushSync(() => setOperation({ kind: "preview", current: 0, total: items.length })); try { const results: Array<{ item: SyncItem; preview: SyncPreview }> = []; for (const [index, item] of items.entries()) { const itemRoot = config.rootDirectories.find((candidate) => candidate.id === item.rootId)!; flushSync(() => setOperation({ kind: "preview", current: index + 1, total: items.length, itemName: item.destinationName })); try { results.push({ item, preview: await api.preview(item, itemRoot.path) }); } catch (cause) { throw new Error(`同步预览失败，GitHub 链接无效或无法访问：${item.sourceUrl}。${errorMessage(cause, "无法获取 GitHub 来源。")}`); } } setPreviews(results); setDialog("preview"); } catch (cause) { setError(errorMessage(cause, "无法生成同步预览。")); } finally { setOperation(undefined); } };
  const sync = async () => { const changes = previews.filter(({ preview }) => preview.changes.length); if (!changes.length) return setDialog(null); flushSync(() => setOperation({ kind: "sync", current: 0, total: changes.length })); let next = config; const failures: string[] = []; for (const [index, { item }] of changes.entries()) { try { const itemRoot = next.rootDirectories.find((candidate) => candidate.id === item.rootId)!; flushSync(() => setOperation({ kind: "sync", current: index + 1, total: changes.length, itemName: item.destinationName })); const updated = await api.sync(item, itemRoot.path); next = { ...next, items: next.items.map((candidate) => candidate.id === updated.id ? updated : candidate) }; } catch (cause) { failures.push(`${item.destinationName}：${errorMessage(cause, "同步失败。")}`); } } await persist(next); setOperation(undefined); setDialog(null); setPreviews([]); failures.length ? setError(failures.join("\n")) : setNotice(`已完成 ${changes.length} 项同步。`); };
  const deleteLocation = async () => { if (!rootId) return; const affected = config.items.filter((item) => item.rootId === rootId && contains(group, item.folderGroup)); if (deleteFiles) await api.deleteDirectories(affected.map((item) => localPath(root, item))); const next = group ? { ...config, folderGroups: config.folderGroups.filter((candidate) => candidate.rootId !== rootId || !contains(group, candidate.path)), items: config.items.filter((item) => item.rootId !== rootId || !contains(group, item.folderGroup)) } : { ...config, rootDirectories: config.rootDirectories.filter((candidate) => candidate.id !== rootId), folderGroups: config.folderGroups.filter((candidate) => candidate.rootId !== rootId), items: config.items.filter((item) => item.rootId !== rootId) }; await persist(next); setLocation(next.rootDirectories[0]?.id ?? ""); setDeleteFiles(false); setDialog(null); };
  const beginMove = async (item: SyncItem, targetRootId: string, targetGroup: string) => { if (item.rootId === targetRootId && item.folderGroup === targetGroup) return; if (config.items.some((candidate) => candidate.id !== item.id && candidate.rootId === targetRootId && itemPath(candidate) === [targetGroup, item.destinationName].filter(Boolean).join("/"))) return setError("目标位置已有同名同步项，请先重命名其中一个。"); const fromRoot = config.rootDirectories.find((candidate) => candidate.id === item.rootId); if (!await api.directoryExists(localPath(fromRoot, item))) { const moved = { ...item, rootId: targetRootId, folderGroup: targetGroup }; await persist({ ...config, items: config.items.map((candidate) => candidate.id === item.id ? moved : candidate) }); setLocation(targetRootId, targetGroup); setSelectedId(item.id); return; } setPendingMove({ item, rootId: targetRootId, group: targetGroup }); setMoveFiles(false); setDialog("move"); };
  const finishMove = async () => { if (!pendingMove) return; const fromRoot = config.rootDirectories.find((candidate) => candidate.id === pendingMove.item.rootId); const toRoot = config.rootDirectories.find((candidate) => candidate.id === pendingMove.rootId); const moved = { ...pendingMove.item, rootId: pendingMove.rootId, folderGroup: pendingMove.group }; try { if (moveFiles) await api.moveDirectory(localPath(fromRoot, pendingMove.item), localPath(toRoot, moved)); await persist({ ...config, items: config.items.map((item) => item.id === moved.id ? moved : item) }); setLocation(moved.rootId, moved.folderGroup); setSelectedId(moved.id); setDialog(null); } catch (cause) { setError(`${errorMessage(cause, "无法移动本地目标目录。")} 已保留原位置配置。`); } };
  const removeItem = async (item: SyncItem) => { try { if (deleteFiles) await api.deleteDirectories([localPath(config.rootDirectories.find((candidate) => candidate.id === item.rootId), item)]); await persist({ ...config, items: config.items.filter((candidate) => candidate.id !== item.id) }); setSelectedId(undefined); setPendingDelete(undefined); setDeleteFiles(false); setDialog(null); } catch (cause) { setError(`${errorMessage(cause, "无法删除本地目标文件夹。")} 同步项配置未删除。`); } };
  const importConfig = async () => { try { const imported = await api.importConfig(); if (!imported) return; if (config.rootDirectories.length || config.folderGroups.length || config.items.length) { setPendingImport(imported); setDialog("import"); } else await persist(imported); } catch (cause) { setError(errorMessage(cause, "无法导入配置。")); } };
  const autoScroll = (event: React.DragEvent) => { if (!draggedId.current) return; const sidebar = sidebarRef.current; const inSidebar = !!sidebar && event.clientX < sidebar.getBoundingClientRect().right; const bounds = inSidebar ? sidebar!.getBoundingClientRect() : { top: 0, height: window.innerHeight }; const y = event.clientY - bounds.top; const amount = y < 64 ? -18 : y > bounds.height - 64 ? 18 : 0; if (amount) (inSidebar ? sidebar! : window).scrollBy({ top: amount }); };
  return <main className="app-shell" data-theme={theme} onDragOverCapture={autoScroll}>
    <aside className="sidebar" ref={sidebarRef}><div className="brand-row"><div className="brand"><span className="brand-mark"><RefreshCw size={15} /></span><span>RepoMirror</span></div><button className="icon-button theme-button" onClick={() => persist({ ...config, theme: theme === "light" ? "dark" : "light" })}>{theme === "light" ? <Moon size={16} /> : <Sun size={16} />}</button></div><div className="sidebar-heading"><span>文件夹组</span><button className="icon-button" onClick={addRoot} title="添加根目录"><FolderPlus size={16} /></button></div><nav className="group-nav">{config.rootDirectories.map((directory) => <RootTree key={directory.id} root={directory} nodes={tree(config.folderGroups.filter((candidate) => candidate.rootId === directory.id).map((candidate) => candidate.path))} activeRootId={rootId} activeGroup={group} items={config.items} draggedId={draggedId} dropTarget={dropTarget} setDropTarget={setDropTarget} expanded={expanded} onToggle={(key) => setExpanded((set) => { const next = new Set(set); next.has(key) ? next.delete(key) : next.add(key); return next; })} onSelect={setLocation} onDrop={beginMove} />)}</nav><button className="sidebar-footer" onClick={() => setDialog("settings")}><Settings2 size={15} /><span>本地配置</span></button></aside>
    <section className="content"><header className="topbar"><div className="heading-copy"><Folder size={20} /><div><h1>{root ? (group ? group.split("/").at(-1) : root.path.split("/").at(-1)) : "选择根目录"}</h1><p>{root ? (group ? `相对路径 /${group}` : root.path) : "从左侧 + 添加一个本地根目录"}</p></div></div><div className="toolbar">{root && <><button className="icon-button danger" onClick={() => { setDeleteFiles(false); setDialog("delete"); }} title="删除当前范围"><Trash2 size={16} /></button><button className="button secondary" onClick={() => setDialog("group")}><FolderPlus size={16} />文件夹组</button><button className="button secondary" onClick={() => setDialog("sources")}><Plus size={16} />添加来源</button><button className="button primary" disabled={!config.items.some((item) => item.rootId === rootId && contains(group, item.folderGroup)) || !!operation} onClick={() => { setRecursive(true); setDialog("sync-scope"); }}><RefreshCw size={16} />同步当前文件夹</button></>}</div></header><div className="list-head"><span>来源与目标</span><span>上次同步结果</span><span>最近同步</span><span /></div><div className="item-list">{!loaded && <div className="empty-state"><LoaderCircle className="spin" size={20} />正在载入配置</div>}{loaded && root && !directItems.length && <div className="empty-state"><Folder size={24} /><strong>这里还没有同步项</strong><span>添加 GitHub 仓库或项目内目录，它会同步到这个位置。</span></div>}{directItems.map((item) => <button draggable className={`item-row ${selectedId === item.id ? "selected" : ""}`} key={item.id} onDragStart={(event) => { draggedId.current = item.id; event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", item.id); }} onDragEnd={() => { draggedId.current = undefined; setDropTarget(undefined); }} onClick={() => setSelectedId(item.id)}><span className="item-title"><Github size={17} /><span><strong>{item.destinationName}</strong><small>{item.sourcePath ? `${item.repoUrl.replace("https://github.com/", "").replace(".git", "")} / ${item.sourcePath}` : item.repoUrl.replace("https://github.com/", "").replace(".git", "")}</small></span></span><Status item={item} /><span className="date">{item.lastSyncedAt ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.lastSyncedAt)) : "从未"}</span><ChevronRight size={17} /></button>)}</div></section>
    {selected && <aside className="details"><div className="detail-top"><div><small>同步项</small><h2>{selected.destinationName}</h2></div><button className="icon-button" onClick={() => setSelectedId(undefined)}><X size={17} /></button></div><div className="detail-path"><Folder size={16} /><span>{localPath(config.rootDirectories.find((candidate) => candidate.id === selected.rootId), selected)}</span></div><label>GitHub 来源<span className="readonly-input">{selected.sourceUrl}</span></label><label>最终文件夹名称<input value={selected.destinationName} onChange={(event) => persist({ ...config, items: config.items.map((item) => item.id === selected.id ? { ...item, destinationName: event.target.value.trim() } : item) })} /></label><label className="switch-row"><span><strong>镜像同步</strong><small>删除来源中不存在的目标文件</small></span><input type="checkbox" checked={selected.mirror} onChange={(event) => persist({ ...config, items: config.items.map((item) => item.id === selected.id ? { ...item, mirror: event.target.checked } : item) })} /></label><div className="detail-actions"><button className="button primary" disabled={!!operation} onClick={() => preview([selected])}><RefreshCw size={16} />预览并同步</button><button className="icon-button danger" onClick={() => { setPendingDelete(selected); setDeleteFiles(false); setDialog("delete-item"); }}><Trash2 size={16} /></button></div></aside>}
    {dialog === "group" && <Modal title="添加文件夹组" close={() => setDialog(null)}><p>路径始终相对当前根目录；例如 <code>a/b/c/d</code>。</p><label>相对根目录的路径<input autoFocus value={groupPath} onChange={(event) => setGroupPath(event.target.value)} onKeyDown={(event) => event.key === "Enter" && addGroup()} /></label><Actions close={() => setDialog(null)} submit={addGroup} label="创建文件夹组" /></Modal>}
    {dialog === "sources" && <Modal title="添加 GitHub 来源" close={() => setDialog(null)}><p>将添加到当前选中的位置：<code>{group || root?.path}</code></p><label>GitHub 链接<textarea autoFocus rows={5} value={urls} onChange={(event) => setUrls(event.target.value)} placeholder={"每行一个链接\nhttps://github.com/owner/repo"} /></label><label>自定义最终名称 <small>仅单条链接</small><input value={customName} onChange={(event) => setCustomName(event.target.value)} /></label><Actions close={() => setDialog(null)} submit={addSources} label="添加同步项" /></Modal>}
    {dialog === "sync-scope" && <Modal title="同步当前文件夹" close={() => setDialog(null)}><p>选择本次同步范围。</p><label className="confirm-row"><input type="radio" checked={!recursive} onChange={() => setRecursive(false)} /><span>仅当前文件夹（{config.items.filter((item) => item.rootId === rootId && item.folderGroup === group).length} 项）</span></label><label className="confirm-row"><input type="radio" checked={recursive} onChange={() => setRecursive(true)} /><span>递归当前文件夹及子文件夹（{config.items.filter((item) => item.rootId === rootId && contains(group, item.folderGroup)).length} 项）</span></label><Actions close={() => setDialog(null)} submit={() => preview(config.items.filter((item) => item.rootId === rootId && (recursive ? contains(group, item.folderGroup) : item.folderGroup === group)))} label="生成同步预览" /></Modal>}
    {dialog === "preview" && <Modal title="同步预览" close={() => setDialog(null)} wide><p>{previews.length} 条同步项已检查；确认后只同步有变更的项目。</p><div className="preview-list">{previews.flatMap(({ item, preview }) => preview.changes.map((change) => <div key={`${item.id}-${change.path}`}><span className={`change change-${change.kind}`}>{change.kind === "add" ? "新增" : change.kind === "modify" ? "修改" : "删除"}</span><code>{itemPath(item)}/{change.path}</code></div>))}</div><Actions close={() => setDialog(null)} submit={sync} label="确认同步" /></Modal>}
    {dialog === "delete" && <Modal title={group ? "删除文件夹组" : "删除根目录"} close={() => setDialog(null)}><p>将递归删除当前范围的文件夹组和同步项配置。本地文件默认保留。</p><label className="confirm-row"><input type="checkbox" checked={deleteFiles} onChange={(event) => setDeleteFiles(event.target.checked)} /><span>同时删除其中同步项管理的本地目标文件夹（不会删除根目录或未管理文件）</span></label><Actions close={() => setDialog(null)} submit={deleteLocation} label={group ? "删除文件夹组" : "删除根目录"} destructive /></Modal>}
    {dialog === "delete-item" && pendingDelete && <Modal title="删除同步项" close={() => setDialog(null)}><p>将删除这条同步链接配置。本地文件夹默认保留。</p><label className="confirm-row"><input type="checkbox" checked={deleteFiles} onChange={(event) => setDeleteFiles(event.target.checked)} /><span>同时删除本地目标文件夹（{localPath(config.rootDirectories.find((candidate) => candidate.id === pendingDelete.rootId), pendingDelete)}）</span></label><Actions close={() => setDialog(null)} submit={() => removeItem(pendingDelete)} label="删除同步项" destructive /></Modal>}
    {dialog === "move" && pendingMove && <Modal title="移动同步项" close={() => setDialog(null)}><p>同步项将迁移到新位置。原文件夹组会保留。</p><label className="confirm-row"><input type="checkbox" checked={moveFiles} onChange={(event) => setMoveFiles(event.target.checked)} /><span>同时移动现有本地目标文件夹；若新位置已有同名文件夹，移动将取消且配置保持原样。</span></label><Actions close={() => setDialog(null)} submit={finishMove} label="确认迁移" /></Modal>}
    {dialog === "settings" && <Modal title="本地配置" close={() => setDialog(null)}><p>根目录与同步项保存在这台 Mac。仅支持新版 JSON 配置。</p><div className="config-actions"><button className="button secondary" onClick={() => api.exportConfig(config)}><Download size={16} />导出 JSON</button><button className="button secondary" onClick={importConfig}><Upload size={16} />导入 JSON</button></div></Modal>}
    {dialog === "import" && pendingImport && <Modal title="替换当前配置" close={() => setDialog(null)}><p>导入会替换当前同步配置，但不会修改任何本地文件。</p><Actions close={() => setDialog(null)} submit={() => { persist(pendingImport); setRootId(pendingImport.rootDirectories[0]?.id); setDialog(null); }} label="替换当前配置" destructive /></Modal>}
    {error && <div className="toast"><CircleAlert size={17} /><span>{error}</span><button className="icon-button" onClick={() => setError(undefined)}><X size={15} /></button></div>}{notice && <div className="toast success"><CircleCheck size={17} /><span>{notice}</span><button className="icon-button" onClick={() => setNotice(undefined)}><X size={15} /></button></div>}{operation && <Progress operation={operation} />}
  </main>;
}
type DropProps = { items: SyncItem[]; draggedId: React.MutableRefObject<string | undefined>; dropTarget?: string; setDropTarget: (target?: string) => void; onDrop: (item: SyncItem, rootId: string, group: string) => void };
function DropRow({ target, children, onDrop, className = "", style, ...props }: DropProps & { target: string; children: React.ReactNode; onDrop: (item: SyncItem) => void; className?: string; style?: React.CSSProperties }) { const finish = (event: React.DragEvent) => { const item = props.items.find((candidate) => candidate.id === (props.draggedId.current ?? event.dataTransfer.getData("text/plain"))); if (item) onDrop(item); props.setDropTarget(undefined); }; return <div className={`tree-row ${className} ${props.dropTarget === target ? "drop-target" : ""}`} style={style} onDragOverCapture={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; props.setDropTarget(target); }} onDragLeaveCapture={(event) => { if (!event.currentTarget.contains(event.relatedTarget as globalThis.Node | null)) props.setDropTarget(undefined); }} onDropCapture={(event) => { event.preventDefault(); finish(event); }}>{children}</div>; }
function RootTree({ root, nodes, activeRootId, activeGroup, expanded, onToggle, onSelect, ...props }: { root: RootDirectory; nodes: Node[]; activeRootId?: string; activeGroup: string; expanded: Set<string>; onToggle: (key: string) => void; onSelect: (rootId: string, group?: string) => void } & DropProps) { const target = `${root.id}:`; return <><DropRow {...props} target={target} className={activeRootId === root.id && !activeGroup ? "active" : ""} onDrop={(item) => props.onDrop(item, root.id, "")}><span className="tree-spacer" /><div className="tree-select" role="button" tabIndex={0} onClick={() => onSelect(root.id)} onKeyDown={(event) => (event.key === "Enter" || event.key === " ") && onSelect(root.id)}><Folder size={15} /><span>{root.path.split("/").at(-1)}</span><em>{props.items.filter((item) => item.rootId === root.id && !item.folderGroup).length}</em></div></DropRow><Tree nodes={nodes} rootId={root.id} active={activeRootId === root.id ? activeGroup : ""} expanded={expanded} onToggle={onToggle} onSelect={onSelect} {...props} /></>; }
function Tree({ nodes, rootId, active, expanded, onToggle, onSelect, depth = 1, ...props }: { nodes: Node[]; rootId: string; active: string; expanded: Set<string>; onToggle: (key: string) => void; onSelect: (rootId: string, group?: string) => void; depth?: number } & DropProps) { return <>{nodes.map((node) => { const key = `${rootId}:${node.path}`; const open = expanded.has(key); const select = () => onSelect(rootId, node.path); return <div className="tree-node" key={key}><DropRow {...props} target={key} className={active === node.path ? "active" : ""} style={{ paddingLeft: 7 + depth * 15 }} onDrop={(item) => props.onDrop(item, rootId, node.path)}>{node.children.length ? <button className="tree-toggle" onClick={() => onToggle(key)}>{open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</button> : <span className="tree-spacer" />}<div className="tree-select" role="button" tabIndex={0} onClick={select} onKeyDown={(event) => (event.key === "Enter" || event.key === " ") && select()}><Folder size={15} /><span>{node.label}</span><em>{props.items.filter((item) => item.rootId === rootId && item.folderGroup === node.path).length}</em></div></DropRow>{open && <Tree nodes={node.children} rootId={rootId} active={active} expanded={expanded} onToggle={onToggle} onSelect={onSelect} depth={depth + 1} {...props} />}</div>; })}</>; }
function Modal({ title, children, close, wide = false }: { title: string; children: React.ReactNode; close: () => void; wide?: boolean }) { return <div className="modal-backdrop"><section className={`modal ${wide ? "wide" : ""}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="icon-button" onClick={close}><X size={17} /></button></header>{children}</section></div>; }
function Actions({ close, submit, label, destructive = false }: { close: () => void; submit: () => void; label: string; destructive?: boolean }) { return <div className="modal-actions"><button className="button ghost" onClick={close}>取消</button><button className={`button ${destructive ? "destructive" : "primary"}`} onClick={submit}><Check size={16} />{label}</button></div>; }
function Progress({ operation }: { operation: Operation }) { return <div className="modal-backdrop progress-backdrop"><section className="progress-dialog"><LoaderCircle size={24} className="spin" /><div><strong>{operation.kind === "preview" ? "正在生成同步预览" : "正在同步文件"}</strong><span>{operation.current} / {operation.total}</span><small>{operation.itemName}</small></div></section></div>; }
